runtime: python39

handlers:
- url: /ask
  script: auto 

- url: /_next/static/
  static_dir: client/.next/static 

- url: /
  static_files: client/out/index.html
  upload: client/out/index.html
  http_headers:
    Cache-Control: public, max-age=0, must-revalidate
  secure: always

- url: /(.*)
  static_files: client/out/\1
  upload: client/out/(.*)
  http_headers:
    Cache-Control: public, max-age=0, must-revalidate
  secure: always

entrypoint: gunicorn -b :$PORT app:app