runtime: python39
entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /ask
  script: auto

- url: /_next/static
  static_dir: client/.next/static

- url: /.*
  static_files: client/.next/server/app/index.html
  upload: client/.next/server/app/index.html